builds:
  - binary: php-fpm_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

dockers:
  - image: hipages/php-fpm_exporter

archive:
  format: binary