builds:
  - binary: php-fpm_exporter
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

dockers:
  - image: hipages/php-fpm_exporter

archive:
  format_overrides:
    - goos: windows
      format: zip